### ISSUE TITLE
Daylight Savings Not Showing (when OWM API is not used)

### ISSUE THREAD

**Issue by mcbrown1010** [daledavies/jump#27]
Issue with daylight savings

The clock in the lower right hand corner shows GMT instead of BST

**Comment by mcbrown1010** [comment]
![image](https://user-images.githubusercontent.com/21295723/163861506-d0927009-adf8-4ba5-829e-25a876850528.png)
In the image you can see the correct time in my taskbar which is an hour earlier than what is shown in jump

**Comment by daledavies** [comment]
That's interesting, I'm in the UK and don't have this problem so can I ask a few questions...

- What timezone is your client in, are you actually in the UK or just quding a latitude and longitude for the UK?
- Could you open your browser's dev tools and paste the json response from /api/weatherdata.php?

**Comment by mcbrown1010** [comment]
I'm in the UK and I have setup the latitude and longitude as the cords of my hometown. my windows PC is displaying the correct time

I have looked in the dev tools and I found this

`DevTools failed to load source map: Could not parse content for https://my.domain.example/assets/css/weather-icons.min.css.map: Unexpected token < in JSON at position 0`

**Comment by daledavies** [comment]
Thanks, I don't use Windows but in both Linux and Android I get the correct time across Firefox, Chrome and Edge. Unfortunately the error you pasted isn't what I need however.

In devtools can you open the network tab and copy the response from `/API/weatherdata.php`?

I can use this to try to reproduce your problem, it should help me to understand what differences there might be between us.

**Comment by daledavies** [comment]
Also are you using the latest release? Docker container or manually installed?

**Comment by mcbrown1010** [comment]
I think I have fixed the issue. The problem was that I didn't use an open weather map API key. I didn't think it would need one for the time. I added the environment variable in docker and its now working

**Comment by daledavies** [comment]
Interesting, thanks for getting back to me. 

Adding the API key will make Jump use the open weather API, the time will be shown for the location provided by the LATLONG parameter, this essentially takes the current UTC time and applies the shift in seconds for the requested location's timezone. Supplying a value for LATLONG effectively does nothing without having an API key supplied.

What I think is happening is that without using the open weather API, Jump actually just displays UTC time rather than applying the local client timezone.

I think I should probably explain this more clearly in the readme, also I can fix the case where the open weather API is not used so time is displayed in the client timezone rather than just showing UTC.

**Comment by daledavies** [comment]
FYI I have included a patch to resolve this, if you pull the latest commits in the main branch you'll see it. 

It will be included in the next release which I will hopefully push to docker hub later this evening.

**Comment by daledavies** [comment]
I've created a new release and tag for v1.1.4 and pushed a new image to docker hub, I hope this works OK for you :)

**Comment by mcbrown1010** [comment]
Yep, Now works without OWM API Key

**Comment by daledavies** [comment]
Awesome, thanks for letting me know.
