### ISSUE TITLE
No icons

### ISSUE THREAD

**Issue by android116** [daledavies/jump#75]
Icons are not displayed. It seems that they are trying to boot - and so on endlessly.
The server is a selfhost and does not have internet access.
How to make the icons show up?
![Снимок экрана_2023-03-02_12-25-42](https://user-images.githubusercontent.com/32191057/222388041-06a4d9f7-225e-4691-8d8e-156ea40dd878.png)

**Comment by daledavies** [comment]
I suspect this might be because the server does not have internet access to retrieve the site's favicons.

You could add your own icons as per the docs here... https://github.com/daledavies/jump#icons

**Comment by daledavies** [comment]
Closing this issue as I can't reproduce and there has been no response

**Comment by JMcrafter26** [comment]
Same problem

**Comment by o---** [comment]
Same problem over here. Just downloaded, fired up the http server, no icons. The sites configuration has not been changed. 
Icons are placed in /sites/icons subdirectory and specified in the sites.json. 

404 >>> http://...../api/icon?siteid=site-10fee05a297b8f117d2bcac0b93a0634

**Comment by speeskeek** [comment]
same here. not using docker - but installed it behind nginx.
since the icon location in the browerser is pointing ot a non-existent location it's comprehendable it shows nothing.

what do I need to put in my nginx config to make this work?

my sites: bartman.duckdns.org/jumpapp

icon location:
bartman.duckdns.org/jumpapp/api/icon?siteid=site-47efbf86396587c527c6f583f65d2c5c

'/var/www/jumpapp' exist
but ' /var/www/jumpapp/api ' doesnt

**Comment by ryancobden** [comment]
Im having the same issue (php 8.2).  I tried adding "#[\AllowDynamicProperties]" which got rid of any and all errors and warnings, but the icons still do not show. This is true whether the icon is local or from dashboard icons.
